[package]
name = "monkey-macros"
version = "0.1.0"
authors = ["Brian Shu <littlebubu.shu@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
darling = "0.12.2"
proc-macro2 = "1.0.24"
quote = "1.0.9"
syn = "1.0.60"

[dev-dependencies]
trybuild = "1.0.41"
